"""Corrections to the tables

Revision ID: 402f3430c409
Revises: 8ca001bf8574
Create Date: 2025-12-26 06:50:31.236398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '402f3430c409'
down_revision = '8ca001bf8574'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('book_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('categories_parent_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'books', ['book_id'], ['id'])
        batch_op.drop_column('parent_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('categories_parent_id_fkey', 'categories', ['parent_id'], ['id'])
        batch_op.drop_column('book_id')

    # ### end Alembic commands ###
