"""Forgot wishlist and its items

Revision ID: 8ca001bf8574
Revises: 7003ba6a7a94
Create Date: 2025-12-26 06:37:15.272479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ca001bf8574'
down_revision = '7003ba6a7a94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wishlists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('share_token', sa.String(length=50), nullable=True),
    sa.Column('privacy', sa.Enum('private', 'shared', 'public', name='wishlist_privacy'), nullable=False),
    sa.Column('event_name', sa.String(length=100), nullable=True),
    sa.Column('event_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_accessed', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('wishlists', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wishlists_share_token'), ['share_token'], unique=True)
        batch_op.create_index(batch_op.f('ix_wishlists_user_id'), ['user_id'], unique=False)

    op.create_table('wishlist_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wishlist_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', 'urgent', name='item_priority'), nullable=False),
    sa.Column('desired_format', sa.String(length=50), nullable=True),
    sa.Column('quantity_desired', sa.Integer(), nullable=True),
    sa.Column('is_purchased', sa.Boolean(), nullable=True),
    sa.Column('purchased_by', sa.Integer(), nullable=True),
    sa.Column('purchased_at', sa.DateTime(), nullable=True),
    sa.Column('purchase_notes', sa.Text(), nullable=True),
    sa.Column('added_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('current_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('lowest_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_drop_alert', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['purchased_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['wishlist_id'], ['wishlists.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wishlist_id', 'book_id', name='uq_wishlist_book')
    )
    with op.batch_alter_table('wishlist_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wishlist_items_book_id'), ['book_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_wishlist_items_wishlist_id'), ['wishlist_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wishlist_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wishlist_items_wishlist_id'))
        batch_op.drop_index(batch_op.f('ix_wishlist_items_book_id'))

    op.drop_table('wishlist_items')
    with op.batch_alter_table('wishlists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wishlists_user_id'))
        batch_op.drop_index(batch_op.f('ix_wishlists_share_token'))

    op.drop_table('wishlists')
    # ### end Alembic commands ###
